# Generated by Django 5.2.1 on 2025-05-18 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 13, 1, 27, 497814, tzinfo=datetime.timezone.utc)),
        ),
    ]
